/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BS
 */
public class cheques extends javax.swing.JFrame {

      Connection con = null;
    PreparedStatement pst= null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    
    public cheques() {
        initComponents();
        con = DBconnect.connect();
        loadtable();
        showdate();
        showtime();
    }
    
     final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd [ E ]");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime(){
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
   
    }
    
    
      public void getlastidfi_a(){
        
                try{
      String q = " SELECT che FROM a ORDER BY che DESC LIMIT 1";
      pst = con.prepareStatement(q);
      rs = pst.executeQuery();

        while(rs.next()){
          // jLabel30.setText("");
            jLabel26.setText(rs.getString("che"));
        }
      
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
        
        
    }
    
    public void loadtable(){
        
        try{
        String a = " select che as Che_No , branc as Branch , amount as Amount , status as Status, bank as Bank , getdate as Get,"
                + " outdate as Outd , returnre as Returnre , subbank as Sub_bank , subbranch as Sub_branch , subacc as Acc_No ,subdate as Sub_date   from a  Order by che" ;
        pst = con.prepareStatement(a);
        rs = pst.executeQuery();
        
        jTable1.setModel (DbUtils.resultSetToTableModel(rs));
        getlastidfi_a();
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    
    /*******************************🐘 BACKGROUND  🐘***************************/
       void setexit(JLabel x){
        x.setBackground(new Color(204,0,0));
        
    }
    void resetexit(JLabel x){
        x.setBackground(new Color(51,51,51));
        
        
        }
    /*******************************🐘 BACKGROUND  🐘***************************/
    
    
    
    
    
    
    
    /*******************************🐘 BACKGROUND  🐘***************************/
    public void setBackgroundpanel(JPanel x){
        x.setBackground(new Color(102,102,102));
        
    }
    
    /*******************************🐘 BACKGROUND  🐘***************************/
    
    
    
    
    
    
    
    //*******************************🐘 BACKGROUND  🐘***************************/
    public void backgroundset(JLabel w){
        w.setBackground(new Color(0,0,0));
               
    }
    
    public void backgroundreset(JLabel q){
        q.setBackground(new Color(102,102,102));
            }
    
    /*******************************🐘 BACKGROUND  🐘***************************/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cheno = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        bank = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        to = new com.toedter.calendar.JDateChooser();
        from = new com.toedter.calendar.JDateChooser();
        reason = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bank2 = new javax.swing.JComboBox<String>();
        acc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        branch2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("<html><font color = \"white\" >Amount :</font></html>");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 80, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("<html><font color = \"white\" >Bank :</font></html>");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("<html><font color = \"white\" >Cheque No :</font></html>");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("<html><font color = \"white\" >Cheque Status :</font></html>");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("<html><font color = \"white\" >Cheque Date FROM :</font></html>");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("<html><font color = \"white\" >Return Reason :</font></html>");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 30));

        cheno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cheno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cheno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chenoActionPerformed(evt);
            }
        });
        cheno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chenoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chenoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chenoKeyTyped(evt);
            }
        });
        jPanel4.add(cheno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, 30));

        amount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        jPanel4.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 30));

        branch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        branch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                branchKeyTyped(evt);
            }
        });
        jPanel4.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, 30));

        status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusKeyPressed(evt);
            }
        });
        jPanel4.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, 30));

        bank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Bank..", "National Savings Bank", "Bank of Ceylon", "Commercial Bank of Ceylon PLC", "Hatton National Bank PLC", "National Development Bank PLC", "Nations Trust Bank PLC", "People's Bank", "Sampath Bank PLC", "Sanasa Development Bank PLC (SDB bank)", "Amana Bank", "Axis Bank Ltd", "Cargills Bank Ltd", "Citibank N.A.", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd", "ICICI Bank Ltd", "Indian Bank", "Indian Overseas Bank", "MCB Bank Ltd", "Pan Asia Banking Corporation PLC", "Public Bank Berhad", "Seylan Bank PLC", "Standard Chartered Bank", "State Bank of India", "The Hong Kong and Shanghai Banking Corporation Ltd (HSBC)", "Union Bank of Colombo PLC", "Housing Development Finance Corporation Bank of Sri Lanka (HDFC)", "Lankaputhra Development Bank Ltd.", "Regional Development Bank (Pradheshiya Sanwardhana Bank) (RDB)", "Sri Lanka Savings Bank Ltd (SLS Bank)", "State Mortgage & Investment Bank (SMIB)", " " }));
        jPanel4.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 190, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("<html><font color = \"white\" >Branch :</font></html>");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 70, 30));
        jPanel4.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 180, 30));
        jPanel4.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, 30));

        reason.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reason.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 430, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("<html><font color = \"white\" >TO :</font></html>");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 40, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("<html><font color = \"white\" >L. Cheque No :</font></html>");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, 30));

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Rs.");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 20, 30));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Cheque Informatin");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 160, 20));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 60, 10));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 630, 350));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("<html><font color = \"white\" >Account No :</font></html>");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("<html><font color = \"white\" >Bank :</font></html>");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        bank2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bank2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Bank..", "National Savings Bank", "Bank of Ceylon", "Commercial Bank of Ceylon PLC", "Hatton National Bank PLC", "National Development Bank PLC", "Nations Trust Bank PLC", "People's Bank", "Sampath Bank PLC", "Sanasa Development Bank PLC (SDB bank)", "Amana Bank", "Axis Bank Ltd", "Cargills Bank Ltd", "Citibank N.A.", "Deutsche Bank AG", "DFCC Bank PLC", "Habib Bank Ltd", "ICICI Bank Ltd", "Indian Bank", "Indian Overseas Bank", "MCB Bank Ltd", "Pan Asia Banking Corporation PLC", "Public Bank Berhad", "Seylan Bank PLC", "Standard Chartered Bank", "State Bank of India", "The Hong Kong and Shanghai Banking Corporation Ltd (HSBC)", "Union Bank of Colombo PLC", "Housing Development Finance Corporation Bank of Sri Lanka (HDFC)", "Lankaputhra Development Bank Ltd.", "Regional Development Bank (Pradheshiya Sanwardhana Bank) (RDB)", "Sri Lanka Savings Bank Ltd (SLS Bank)", "State Mortgage & Investment Bank (SMIB)", " " }));
        jPanel3.add(bank2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, 30));

        acc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        acc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accKeyTyped(evt);
            }
        });
        jPanel3.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("<html><font color = \"white\" >Branch :</font></html>");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 30));

        branch2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branch2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(branch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Submit Date :");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 40));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, 30));

        jButton1.setFont(new java.awt.Font("Anklepants", 0, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 200, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 160, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 160, 30));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Submit To Bank");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 150, 20));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 60, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 650, 350));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1280, 190));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("<html><font color = \"white\" >Acc.No :</font></html>");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 40));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 30));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/2-Hot-Printer-icon.png"))); // NOI18N
        jLabel64.setToolTipText("See All");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 50));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Blue-Backup-B-icon(1).png"))); // NOI18N
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 40, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 100, 30));
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, 30));
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 40, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Refresh Table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 220, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1300, 250));

        time.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 0));
        time.setText("time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 120, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 0));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 140, 20));

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CHEQUES DETAILS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 270, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/go_previous_blue.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 180, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Apps-Home-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chenoActionPerformed

    private void chenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chenoKeyPressed
        char inumber = evt.getKeyChar();
        if(inumber == KeyEvent.VK_DOWN){
            status.requestFocus();
        }
    }//GEN-LAST:event_chenoKeyPressed

    private void chenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chenoKeyReleased
        /*  if(evt.getKeyCode()== 10){
            d.requestFocus();
        }
        */
    }//GEN-LAST:event_chenoKeyReleased

    private void chenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chenoKeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACKSPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_chenoKeyTyped

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        char inum = evt.getKeyChar();
        if(!(Character.isDigit(inum) || (inum == KeyEvent.VK_DELETE) || (inum == KeyEvent.VK_BACKSPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_amountKeyTyped

    private void branchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_branchKeyTyped
        char num = evt.getKeyChar();
        if((Character.isDigit(num))){
            evt.consume();
        }
    }//GEN-LAST:event_branchKeyTyped

    private void statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusKeyPressed
        /*if(evt.getKeyCode()== 28){
            a.requestFocus();*/
    }//GEN-LAST:event_statusKeyPressed

    private void accKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accKeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACKSPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_accKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(row, 0).toString());
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        try{

            String sql = " select * from a where che = '"+click+"' " ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){

                String a1 = rs.getString("che");
                cheno.setText(a1);

                String a2 = rs.getString("branc");
                branch.setText(a2);

                String a3 = rs.getString("amount");
                amount.setText(a3);

                String a4 = rs.getString("status");
                status.setText(a4);

                String a5 = rs.getString("bank");
                bank.setSelectedItem(a5);

                String a6 = rs.getString("returnre");
                reason.setText(a6);

                String a7 = rs.getString("subbank");
                bank2.setSelectedItem(a7);

                String a8 = rs.getString("subbranch");
                branch2.setText(a8);

                String a9 = rs.getString("subacc");
                acc.setText(a9);
                
                  ((JTextField)from.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 5).toString());

                  ((JTextField)to.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 6).toString());
                  
                  ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 11).toString());
                
                
                

            }}catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        String acc = jTextField5.getText();
        try{

            String q = " select * from a where subacc like '%"+acc+"%'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int x = JOptionPane.showConfirmDialog(null, "Do You Want To Store These Data? ","add to DB",JOptionPane.INFORMATION_MESSAGE);

        if( x == 0){

            try{

           
               
               String che = cheno.getText();
               String branc = branch.getText();
               String amou = amount.getText();
               String statu = status.getText();
               String ban = bank.getSelectedItem().toString();
               
                String fro = ((JTextField)from.getDateEditor().getUiComponent()).getText();
              String t = ((JTextField)to.getDateEditor().getUiComponent()).getText();
               String retre = reason.getText();
               
               String subbank = bank2.getSelectedItem().toString();
               String subbranch = branch2.getText();
               String subacc = acc.getText();
               String subdate = ((JTextField)from.getDateEditor().getUiComponent()).getText();
               
               String sql = " insert into a ( che,branc,amount,status,bank,getdate,outdate,returnre,subbank,subbranch,subacc , subdate) "
                       + "values ('"+che+"' , '"+branc+"' , '"+amou+"' , '"+statu+"' , "
                       + " '"+ban+"' , '"+fro+"' , '"+t+"' , '"+retre+"' , '"+subbank+"' , '"+subbranch+"' , '"+subacc+"' , '"+subdate+"')";    
                                           
                pst = con.prepareStatement(sql);
                pst.execute();
                
//                   String sq = " insert into fi_cheque_backup ( che,branc,amount,status,bank,getdate,outdate,returnre,subbank,subbranch,subacc ,subdate) "
//                       + "values ('"+che+"' , '"+branc+"' , '"+amou+"' , '"+statu+"' , "
//                       + " '"+ban+"' , '"+fro+"' , '"+t+"' , '"+retre+"' , '"+subbank+"' , '"+subbranch+"' , '"+subacc+"' , '"+subdate+"')";  
                
//                   pst = con.prepareStatement(sq);
//                   pst.execute();
                
                   
                   
                JOptionPane.showMessageDialog(null,"Complete!");
                loadtable();
                getlastidfi_a();
                
                    cheno.setText("");
                    amount.setText("");
                    bank.setSelectedItem(0);
                    branch.setText("");
                    status.setText("");
                    from.setDate(null);
                    to.setDate(null);
                    reason.setText("");
                    bank2.setSelectedItem(0);
                    branch2.setText("");
                    acc.setText("");
                    jDateChooser1.setDate(null);
        
                

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Try again!");

            }
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(row, 0).toString());
        
        
               String che = cheno.getText();
               String branc = branch.getText();
               String amou = amount.getText();
               String statu = status.getText();
               String ban = bank.getSelectedItem().toString();
               
               Date fro = from.getDate();
               Date t = to.getDate();
               String retre = reason.getText();
               
               String subbank = bank2.getSelectedItem().toString();
               String subbranch = branch2.getText();
               String subacc = acc.getText();
               Date subdate = jDateChooser1.getDate();
        
        int x = JOptionPane.showConfirmDialog(null, "Do u want to delete? ");
        
        if( x == 0){
            
            try{
                
                
                
                 String sql = " insert into fi_delete_cheque ( che,branc,amount,status,bank,getdate,outdate,returnre,subbank,subbranch,subacc,subdate) "
                       + "values ('"+che+"' , '"+branc+"' , '"+amou+"' , '"+statu+"' , "
                       + " '"+ban+"' , '"+fro+"' , '"+t+"' , '"+retre+"' , '"+subbank+"' , '"+subbranch+"' , '"+subacc+"' , '"+subdate+"')";    
                                           
                pst = con.prepareStatement(sql);
                pst.execute();
                
                String q = " delete from a where che = '"+click+"'";
                pst = con.prepareStatement(q);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, " Complete!");
                loadtable();
                getlastidfi_a();
                
                    cheno.setText("");
                    amount.setText("");
                    bank.setSelectedIndex(0);
                    branch.setText("");
                    status.setText("");
                    from.setDate(null);
                    to.setDate(null);
                    reason.setText("");
                    bank2.setSelectedIndex(0);
                    branch2.setText("");
                    acc.setText("");
                    jDateChooser1.setDate(null);
                
                
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"try");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         cheno.setText("");
        amount.setText("");
        branch.setText("");
        status.setText("");
        reason.setText("");
        branch2.setText("");
        acc.setText("");
        bank.setSelectedIndex(0);
        bank2.setSelectedIndex(0);
        from.setDate(null);
        to.setDate(null);
         jDateChooser1.setDate(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked

        
        try{

            String sq1 = " select * from  fi_delete_cheque where che= '"+jTextField3.getText()+"'";
            pst = con.prepareStatement(sq1);
            rs = pst.executeQuery();

            if(rs.next()){
                 String a1 = rs.getString("che");
                

                String a2 = rs.getString("branc");
                

                String a3 = rs.getString("amount");
                

                String a4 = rs.getString("status");
                

                String a5 = rs.getString("bank");
                

                String a6 = rs.getString("returnre");
               

                String a7 = rs.getString("subbank");
                

                String a8 = rs.getString("subbranch");
                

                String a9 = rs.getString("subacc");
                
                
                String a10 = rs.getString("getdate");
                
                
                String a11 = rs.getString("outdate");
                
                String a12 = rs.getString("subdate");
                
                
                
                   String sql = " insert into a ( che,branc,amount,status,bank,getdate,outdate,returnre,subbank,subbranch,subacc , subdate) "
                       + "values ('"+a1+"' , '"+a2+"' , '"+a3+"' , '"+a4+"' , "
                       + " '"+a5+"' , '"+a10+"' , '"+a11+"' , '"+a6+"' , '"+a7+"' ,"
                           + " '"+a8+"' , '"+a9+"' , '"+a12+"')";   
                   
                   pst = con.prepareStatement(sql);
                   pst.execute();
                   
                String q = " delete from fi_delete_cheque where che = '"+jTextField3.getText()+"'";
                pst = con.prepareStatement(q);
                pst.execute();
                
                
                JOptionPane.showMessageDialog(null, "complete");
                loadtable();
                
            }
            }catch(Exception e){
                
                    JOptionPane.showMessageDialog(null, e);
                    }
                
            
        
    }//GEN-LAST:event_jLabel48MouseClicked
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int row = jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(row, 0).toString());
        
         int x = JOptionPane.showConfirmDialog(null, "Do You Want To Update These Data? ","add to DB",JOptionPane.INFORMATION_MESSAGE);

        if( x == 0){
        
        
               String che = cheno.getText();
               String branc = branch.getText();
               String amou = amount.getText();
               String statu = status.getText();
               String ban = bank.getSelectedItem().toString();
               
               Date fro = from.getDate();
               Date t = to.getDate();
               String retre = reason.getText();
               
               String subbank = bank2.getSelectedItem().toString();
               String subbranch = branch2.getText();
               String subacc = acc.getText();
               Date subdate = jDateChooser1.getDate();
        
               try{
               
                String q = " delete from a where che = '"+click+"'";
                pst = con.prepareStatement(q);
                pst.execute();
                   
                   
                String sql = " insert into a ( che,branc,amount,status,bank,getdate,outdate,returnre,subbank,subbranch,subacc,subdate) "
                       + "values ('"+che+"' , '"+branc+"' , '"+amou+"' , '"+statu+"' , "
                       + " '"+ban+"' , '"+fro+"' , '"+t+"' , '"+retre+"' , '"+subbank+"' , '"+subbranch+"' , "
                        + "'"+subacc+"' , '"+subdate+"')";    
                                           
                pst = con.prepareStatement(sql);
                pst.execute();
                
                loadtable();
                JOptionPane.showMessageDialog(null, "complete");
                
        cheno.setText("");
        amount.setText("");
        branch.setText("");
        status.setText("");
        reason.setText("");
        branch2.setText("");
        acc.setText("");
        bank.setSelectedIndex(0);
        bank2.setSelectedIndex(0);
        from.setDate(null);
        to.setDate(null);
        jDateChooser1.setDate(null);
                
        
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
               } }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        Fi_Main am = new Fi_Main();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Home ho = new Home();
        ho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        MessageFormat header = new MessageFormat("Report Print!");
        MessageFormat foter = new MessageFormat("page{0,number,integer}");

        try{

            jTable1.print(JTable.PrintMode.NORMAL,header,foter);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Try Again"); }
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
       char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACKSPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadtable();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cheques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> bank;
    private javax.swing.JComboBox<String> bank2;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField branch2;
    private javax.swing.JTextField cheno;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField reason;
    private javax.swing.JTextField status;
    private javax.swing.JLabel time;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
