/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sri
 */
public class emp_sal extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    double bes;
    double ove;
    double bon;
    double gross;
    /**
     * Creates new form emp_sal
     */
    public emp_sal() {
        initComponents();
        
        //db
        con = DBconnect.connect();
        
        tableload();
        
        showdate();
        showtime();
        
    }
    
    //***********************************************Phone Validation************************************//  
    
    boolean validatePhone(String val)
    {
        if(val.startsWith("07") || val.startsWith("+94"))
        {
            if(val.startsWith("+94"))
            {
                if(val.length()==12)
                {
                    return true;
                }
                else return false;
            }
            else if(val.length()==10)
            {
                return true;
            }
            else return false;
        }
        String ph_pattern="^\\+?[0-9.()-](10,25)$";
        if(val.length()==10)
        {
            return true;
        }
    else return false;
    }    
   
    //***********************************************NIC Validation************************************//
     
     boolean validateNIC(String val)
     {
         String nic_pattern="^[0-9]{9}V$";
         if(val.matches(nic_pattern))
         {
             return true;
         }
         else return false;
     }
    
    //***********************************************Table Loade************************************// 
     
        public void tableload()
    {
        try{
        String lod = "SELECT * from emp_sal";
        pst = con.prepareStatement(lod);
        rs = pst.executeQuery();
        
        table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       }
    
        /********************** DATE AND TIME *********************************/
        final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime(){
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
   
    }
    /********************** DATE AND TIME *********************************/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b2 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        b8 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b5 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        b14 = new javax.swing.JTextField();
        b18 = new javax.swing.JTextField();
        b19 = new javax.swing.JTextField();
        b16 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        b15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        b17 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        b12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        b13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b9 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        b11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 219, 60));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newicon/cal1.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 60));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newicon/clock2.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 80));

        date.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("date");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 150, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newicon/WhatsApp Image 2018-03-06 at 5.07.21 PM.jpeg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 20, 490, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newicon/employee.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 70, 80));

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newicon/cancel.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 30, 30));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LogOut");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, 60, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Salary");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 130, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bola/rsz_1go_previous_blue.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 50, 80));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NIC/CID/Tel/Name");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 20));

        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField15KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 210, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1170, 130));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 80, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 70, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 1210, 210));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, 20));

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("First Name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Employee Id");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Phone Number");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Nic Number");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, 20));

        b4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 20));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Address");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Line 1");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Linee 2");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("City");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        b8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, 20));

        b7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 20));

        b6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 20));

        b5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Gender");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 350, 330));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Add table");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gross pay");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Incentives");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Net pay");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, 20));

        b14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel6.add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, 30));

        b18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 160, 30));

        b19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(b19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 160, 30));

        b16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        jPanel6.add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 160, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ETF");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 20));

        b15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 160, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("EPF");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 30, 20));

        b17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        jPanel6.add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 160, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Deducation");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 20));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/pdf-icon.png"))); // NOI18N
        jLabel57.setToolTipText("See All");
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 50));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 810, 160));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Overtime");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        b12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("H:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        b13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel3.add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("working days");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Departmant");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        b9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Finances", "Designers", "Stores", "Drivers", "Labers" }));
        b9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel3.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Add paymant ");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 120, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Reset");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 70, 30));

        b11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel3.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 150, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Besic salary");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, -1));

        b10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Bonus ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Rs:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 20, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Rs:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 810, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bola/black_background_pattern_light_texture_55291_1920x1200.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new emp_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyReleased

        String name = jTextField15.getText();
      //  String nic = jTextField15.getText();
      //  String tel = jTextField15.getText();
        try
        {
            String sql ="select id,name,l1,l2,city,gen,tel,daduc,besic,over,"
            + "bonus,gpay,dedu,npay,epf,ets from emp_sal where name LIKE '%"+name+"%'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField15KeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int ro = table.getSelectedRow();

        String eid  = table.getValueAt(ro,0).toString();
        String nam  = table.getValueAt(ro,1).toString();
        String nic  = table.getValueAt(ro,2).toString();
        String tel  = table.getValueAt(ro,3).toString();
        String gen  = table.getValueAt(ro,4).toString();
        String l1  = table.getValueAt(ro,5).toString();
        String l2  = table.getValueAt(ro,6).toString();
        String cit = table.getValueAt(ro,7).toString();
        String dep = table.getValueAt(ro,8).toString();
        String bes = table.getValueAt(ro,9).toString();
        String wday  = table.getValueAt(ro,10).toString();
        String over = table.getValueAt(ro,11).toString();
        String bon = table.getValueAt(ro,12).toString();
        String gro = table.getValueAt(ro,13).toString();
        String epf = table.getValueAt(ro,14).toString();
        String etf = table.getValueAt(ro,15).toString();
        String dedu = table.getValueAt(ro,16).toString();
        String ins = table.getValueAt(ro,17).toString();
        String net = table.getValueAt(ro,18).toString();

        b1.setText(eid);
        b2.setText(nam);
        b3.setText(nic);
        b4.setText(tel);
        b5.setSelectedItem(gen);
        b6.setText(l1);
        b7.setText(l2);
        b8.setText(cit);
        b9.setSelectedItem(dep);
        b10.setText(bes);
        b11.setText(wday);
        b12.setText(over);
        b13.setText(bon);
        b14.setText(gro);
        b15.setText(epf);
        b16.setText(etf);
        b17.setText(dedu);
        b18.setText(ins);
        b19.setText(net);
    }//GEN-LAST:event_tableMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        int x = JOptionPane.showConfirmDialog(null,"Are You Sure  ?");
        
        String test = b4.getText();
        String ni = b3.getText();
        
        if(validatePhone(test))
        {
                if(validateNIC(ni))
                {
        
        if(x==0)
                 {
                    String eid = b1.getText();
                    String nam = b2.getText();
                    String nic = b3.getText();
                    String tel = b4.getText();
                    String gen = (String) b5.getSelectedItem();
                    String l1 = b6.getText();
                    String l2 = b7.getText();
                    String cit = b7.getText();
                    String dep = (String) b9.getSelectedItem();
                    String bes = b10.getText();
                    String wday = b11.getText();
                    String over = b12.getText();
                    String bon = b13.getText();
                    String gro = b14.getText();
                    String epf = b15.getText();
                    String etf = b16.getText();
                    String dedu = b17.getText();
                    String ins = b18.getText();
                    String net  = b19.getText();

            try
            {
                String sq = "UPDATE emp_sal SET Emp_Id = '"+eid+"',Name='"+nam+"',nic='"+nic+"',tel='"+tel+"',"
                + "gende='"+gen+"',l1='"+l1+"',l2='"+l2+"',city='"+cit+"',depart='"+dep+"',besic='"+bes+"',"
                + "work_days='"+wday+"',over_time='"+over+"',bonus='"+bon+"',gros='"+gro+"',"
                + "epf='"+epf+"',etf='"+etf+"',dedu='"+dedu+"',ins='"+ins+"',net_pay='"+net+"' WHERE Emp_Id = '"+eid+"'";

                pst = con.prepareStatement(sq);
                pst.execute();

                tableload();
                JOptionPane.showMessageDialog(this," Update Successfull  !");

                b1.setText(null);
                b2.setText(null);
                b3.setText(null);
                b4.setText(null);
                b5.setSelectedIndex(0);
                b6.setText(null);
                b7.setText(null);
                b8.setText(null);
                b9.setSelectedIndex(0);
                b10.setText(null);
                b11.setText(null);
                b12.setText(null);
                b13.setText(null);
                b14.setText(null);
                b15.setText(null);
                b16.setText(null);
                b17.setText(null);
                b18.setText(null);
                b19.setText(null);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this," Update Unsuccessfull  !");
                System.out.println(e);
            }
            }
        } 
                else 
                {
                 JOptionPane.showMessageDialog(this," Nic Number Invalide  !");
                }
              } 
              else 
             {
                 JOptionPane.showMessageDialog(this," Phone Number Invalide  !");
             }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        int y = JOptionPane.showConfirmDialog(null," Are You Sure  ?");

        if(y==0)
        {
            String eid = b1.getText();
            try{
                String sql ="DELETE from emp_sal where Emp_Id = '"+eid+"'";
                pst = con.prepareStatement(sql);
                pst.execute();

                tableload();
                JOptionPane.showMessageDialog(this," Delete Successfull  !");
                //         lastid();

                b1.setText(null);
                b2.setText(null);
                b3.setText(null);
                b4.setText(null);
                b5.setSelectedIndex(0);
                b6.setText(null);
                b7.setText(null);
                b8.setText(null);
                b9.setSelectedIndex(0);
                b10.setText(null);
                b11.setText(null);
                b12.setText(null);
                b13.setText(null);
                b14.setText(null);
                b15.setText(null);
                b16.setText(null);
                b17.setText(null);
                b18.setText(null);
                b19.setText(null);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this," Delete Unsuccessfull  !");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        String test = b4.getText();
        String ni = b3.getText();
        
        if(validatePhone(test))
        {
                if(validateNIC(ni))
                {
       
        
        String eid  = b1.getText();
        String nam  = b2.getText();
        String nic  = b3.getText();
        String tel  = b4.getText();
        String gen  = (String) b5.getSelectedItem();
        String l1   = b6.getText();
        String l2   = b7.getText();
        String cit  = b8.getText();
        String dep  = (String) b9.getSelectedItem();
        String bes  = b10.getText();
        String wday = b11.getText();
        String over = b12.getText();
        String bon  = b13.getText();
        String gro  = b14.getText();
        String epf = b15.getText();
        String etf = b16.getText();
        String dedu = b17.getText();
        String ins = b18.getText();
        String net  = b19.getText();

        try
        {
            String ep = "INSERT INTO emp_sal (Emp_Id,Name,nic,tel,gende,l1,l2,city,depart,besic,work_days,over_time,"
            + "bonus,gros,epf,etf,dedu,ins,net_pay) values ('"+eid+"','"+nam+"','"+nic+"','"+tel+"','"+gen+"','"+l1+"','"+l2+"',"
            + "'"+cit+"','"+dep+"','"+bes+"','"+wday+"','"+over+"','"+bon+"','"+gro+"','"+epf+"','"+etf+"','"+dedu+"','"+ins+"','"+net+"')";
            pst = con.prepareStatement(ep);
            pst.execute();

            tableload();
            
            JOptionPane.showMessageDialog(this,"  Successfuly Added  ! ");

            b1.setText(null);
            b2.setText(null);
            b3.setText(null);
            b4.setText(null);
            b5.setSelectedIndex(0);
            b6.setText(null);
            b7.setText(null);
            b8.setText(null);
            b9.setSelectedIndex(0);
            b10.setText(null);
            b11.setText(null);
            b12.setText(null);
            b13.setText(null);
            b14.setText(null);
            b15.setText(null);
            b16.setText(null);
            b17.setText(null);
            b18.setText(null);
            b19.setText(null);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this," Unsuccessfull Add  !");
            System.out.println(e);
        }
           } 
                else 
                {
                    JOptionPane.showMessageDialog(this," Nic Number Invalide  !");
                }
            } 
            else 
            {
                 JOptionPane.showMessageDialog(this," Phone Number Invalide  !");
            }
         
           
    }//GEN-LAST:event_jButton3MouseClicked

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b17ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         double fi,de,st,dr,la;

        try{
        if(b9.getSelectedItem().equals("Finances"))
        {
           fi = 23000.00;
           String dedu = String.format("%.2f",fi);
           b10.setText(dedu);
        }
        else if(b9.getSelectedItem().equals("Designers"))
        {
           de = 22000.00;
           String dedu = String.format("%.2f",de);
           b10.setText(dedu);
        }
        else if(b9.getSelectedItem().equals("Stores"))
        {
           st = 20000.00;
           String dedu = String.format("%.2f",st);
           b10.setText(dedu);
        }
        else if(b9.getSelectedItem().equals("Drivers"))
        {
           dr = 18000.00;
           String dedu = String.format("%.2f",dr);
           b10.setText(dedu);
        }
        else if(b9.getSelectedItem().equals("Labers"))
        {
           la = 15000.00;
           String dedu = String.format("%.2f",la);
           b10.setText(dedu);
        }
        
        }
        catch(Exception e){}
        
                                   
    }//GEN-LAST:event_b9ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        double over,epf,etf,dedu;
        double total;

        bes = Double.parseDouble(b10.getText());
        ove = Double.parseDouble(b12.getText());
        bon = Double.parseDouble(b13.getText());
        gross = bes;

        String gp = String.format("%.2f",gross);
        b14.setText(gp);

        try
        {
            if (b9.getSelectedItem().equals("Finances"))
            {
                over=((23000/240*1.5)*ove)+bon;
                epf=(bes*8/100)+(bes*12/100);
                etf=(bes*3/100);
                dedu = (bes*8/100);

                String ep = String.format("%.2f",epf);
                b15.setText(ep);

                String et = String.format("%.2f",etf);
                b16.setText(et);

                String de = String.format("%.2f",dedu);
                b17.setText(de);

                String ov = String.format("%.2f",over);
                b18.setText(ov);

                total = gross-dedu+over;
                String to = String.format("%.2f",total);
                b19.setText(to);

            }
            else if (b9.getSelectedItem().equals("Designers"))
            {
                over=((22000/240*1.5)*ove)+bon;
                epf=(bes*8/100)+(bes*12/100);
                etf=(bes*3/100);
                dedu = (bes*8/100);

                String ep = String.format("%.2f",epf);
                b15.setText(ep);

                String et = String.format("%.2f",etf);
                b16.setText(et);

                String de = String.format("%.2f",dedu);
                b17.setText(de);

                String ov = String.format("%.2f",over);
                b18.setText(ov);

                total = gross-dedu+over;
                String to = String.format("%.2f",total);
                b19.setText(to);
            }
            else if (b9.getSelectedItem().equals("Stores"))
            {
                over=((20000/240*1.5)*ove)+bon;
                epf=(bes*8/100)+(bes*12/100);
                etf=(bes*3/100);
                dedu = (bes*8/100);

                String ep = String.format("%.2f",epf);
                b15.setText(ep);

                String et = String.format("%.2f",etf);
                b16.setText(et);

                String de = String.format("%.2f",dedu);
                b17.setText(de);

                String ov = String.format("%.2f",over);
                b18.setText(ov);

                total = gross-dedu+over;
                String to = String.format("%.2f",total);
                b19.setText(to);
            }
            else if (b9.getSelectedItem().equals("Drivers"))
            {
                over=((18000/240*1.5)*ove)+bon;
                epf=(bes*8/100)+(bes*12/100);
                etf=(bes*3/100);
                dedu = (bes*8/100);

                String ep = String.format("%.2f",epf);
                b15.setText(ep);

                String et = String.format("%.2f",etf);
                b16.setText(et);

                String de = String.format("%.2f",dedu);
                b17.setText(de);

                String ov = String.format("%.2f",over);
                b18.setText(ov);

                total = gross-dedu+over;
                String to = String.format("%.2f",total);
                b19.setText(to);
            }
            else if (b9.getSelectedItem().equals("Labers"))
            {
                over=((15000/240*1.5)*ove)+bon;
                epf=(bes*8/100)+(bes*12/100);
                etf=(bes*3/100);
                dedu = (bes*8/100);

                String ep = String.format("%.2f",epf);
                b15.setText(ep);

                String et = String.format("%.2f",etf);
                b16.setText(et);

                String de = String.format("%.2f",dedu);
                b17.setText(de);

                String ov = String.format("%.2f",over);
                b18.setText(ov);

                total = gross-dedu+over;
                String to = String.format("%.2f",total);
                b19.setText(to);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
      
        b1.setText(null);
        b2.setText(null);
        b3.setText(null);
        b4.setText(null);
        b5.setSelectedIndex(0);
        b6.setText(null);
        b7.setText(null);
        b8.setText(null);
        b9.setSelectedIndex(0);
        b10.setText(null);
        b11.setText(null);
        b12.setText(null);
        b13.setText(null);
        b14.setText(null);
        b15.setText(null);
        b16.setText(null);
        b17.setText(null);
        b18.setText(null);
        b19.setText(null);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked

        MessageFormat header = new MessageFormat("Report Print!");
        MessageFormat foter = new MessageFormat("page{0,number,integer}");

        try{

            table.print(JTable.PrintMode.NORMAL,header,foter);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Try Again");
        }
    }//GEN-LAST:event_jLabel57MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_sal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JLabel b10;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b13;
    private javax.swing.JTextField b14;
    private javax.swing.JTextField b15;
    private javax.swing.JTextField b16;
    private javax.swing.JTextField b17;
    private javax.swing.JTextField b18;
    private javax.swing.JTextField b19;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JComboBox<String> b5;
    private javax.swing.JTextField b6;
    private javax.swing.JTextField b7;
    private javax.swing.JTextField b8;
    private javax.swing.JComboBox<String> b9;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTable table;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
