/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BS
 */
public class fi_salari extends javax.swing.JFrame {

    ResultSet rs = null;
    PreparedStatement pst = null;
    Connection con = null;
    
    public fi_salari() {
        initComponents();
        con = DBconnect.connect();
        
        showdate();
        showtime();
    
        loadtable();
        fill();
        
        getlastidfisala();
    }
    
         public void getlastidfisala(){
        
                try{
      String q = " SELECT no FROM fi_inputlast ORDER BY no DESC LIMIT 1";
      pst = con.prepareStatement(q);
      rs = pst.executeQuery();

      while(rs.next()){
      //jLabel30.setText("");
      jLabel2.setText(rs.getString("no"));
        }
      
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    
         }
    
    void fill(){
    jComboBox1.removeAllItems();
        try {
            ResultSet rs = DB.getData("SELECT Emp_Id from emp_sal");
            while (rs.next()) {             
                
                jComboBox1.addItem(rs.getString("Emp_Id"));
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    
    }
    
    void loadtable(){
        
            try{
                String sql = " select * from fi_inputlast ";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                getlastidfisala();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    
    
     final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd [ E ]");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime(){
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        basic = new javax.swing.JTextField();
        workingdays = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        department = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        incentives = new javax.swing.JTextField();
        netpay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        overtime = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bonus = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        grosspay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        epf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        etf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        deducation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namee = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Emp_ID", "Name", "NIC", "Department", "Besic", "Bonus", "Net_Pay", "Date", "Status"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1270, 210));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Emp_ID :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField18KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Refresh Table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 220, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimages/pdf-icon.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 1290, 270));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Department :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Basic Salary :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Working Days :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 30));

        basic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        basic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                basicKeyTyped(evt);
            }
        });
        jPanel1.add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 100, 30));

        workingdays.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workingdays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                workingdaysKeyTyped(evt);
            }
        });
        jPanel1.add(workingdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 100, 30));

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("EMPLOYEE SALARY MAMAGEMENT");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 10));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Employee ID :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jComboBox1.setBackground(new java.awt.Color(51, 255, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setBackground(new java.awt.Color(51, 255, 0));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One :-", "Confirmed And Pay", "Recheck Again" }));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 255, 0));
        jLabel23.setText("PAY SALARY");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 30));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 220, 100));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Date :");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 50, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Net Pay :");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 70, 30));
        jPanel5.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 140, 30));

        department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Finances", "Designers", "Stores", "Drivers", "Labers", " ", " " }));
        jPanel5.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 30));

        jButton2.setFont(new java.awt.Font("Anklepants", 0, 18)); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 140, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 120, 120, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, 120, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 120, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Incentives :");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 80, 30));

        incentives.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(incentives, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 140, 30));

        netpay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        netpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                netpayKeyTyped(evt);
            }
        });
        jPanel5.add(netpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 140, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Over Time :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 80, 30));

        overtime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        overtime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                overtimeKeyTyped(evt);
            }
        });
        jPanel5.add(overtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 140, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bonus :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 60, 30));

        bonus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonusKeyTyped(evt);
            }
        });
        jPanel5.add(bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 140, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gross Pay :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, 30));

        grosspay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grosspay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grosspayKeyTyped(evt);
            }
        });
        jPanel5.add(grosspay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 140, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EPF :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 40, 30));

        epf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        epf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                epfKeyTyped(evt);
            }
        });
        jPanel5.add(epf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 140, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ETF :");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 40, 30));

        etf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etfKeyTyped(evt);
            }
        });
        jPanel5.add(etf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 140, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Deducation :");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 80, 30));

        deducation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deducation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deducationKeyTyped(evt);
            }
        });
        jPanel5.add(deducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 140, 30));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, 30));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, 30));

        namee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 190, 30));

        nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1310, 290));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Net Pay :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 70, 30));

        time.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 0));
        time.setText("time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 110, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 0));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 130, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/go_previous_blue.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Apps-Home-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyReleased
        String did = jTextField18.getText();

        try{

            String q = " Select * from fi_inputlast where Emp_ID like '%"+did+"%'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();

            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField18KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String tmp = jComboBox1.getSelectedItem().toString();
       String sql = " select * from emp_sal where Emp_Id = ? ";
       
       try{
           pst = con.prepareStatement(sql);
           pst.setString(1, tmp);
           rs = pst.executeQuery();
           
           if ( rs.next()){
                
                 String add3 = rs.getString("Emp_Id");
                jComboBox1.setSelectedItem(add3);
               
               
                String add4 = rs.getString("Name");
                namee.setText(add4);
                
                String add5 = rs.getString("nic");
                nic.setText(add5);
                
                String add6 = rs.getString("besic");
                basic.setText(add6);
                
                String add7 = rs.getString("work_days");
                workingdays.setText(add7);
                
                
                
                
                
                String add8 = rs.getString("over_time");
                overtime.setText(add8);
                
                String add9 = rs.getString("bonus");
                bonus.setText(add9);
                
                String ad10 = rs.getString("gros");
                grosspay.setText(ad10);
                
                String ad11 = rs.getString("epf");
                epf.setText(ad11);
                
                
                
                
                String add12 = rs.getString("etf");
                etf.setText(add12);
                
                String add13 = rs.getString("dedu");
                deducation.setText(add13);
                
                String ad14 = rs.getString("ins");
                incentives.setText(ad14);
                
                String ad15 = rs.getString("net_pay");
                netpay.setText(ad15);
                
                String ad16 = rs.getString("depart");
                department.setSelectedItem(ad16);
                
                
                
               
           }
       }
           catch (Exception e){
                   JOptionPane.showMessageDialog(null, e);
                   }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String empid = jComboBox1.getSelectedItem().toString();
        String na = namee.getText();
        String ni = nic.getText();
        String depa = department.getSelectedItem().toString();
        String bas = basic.getText();
        String bon  = bonus.getText();
        String net  = netpay.getText();
       String nduedate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String stat = jComboBox3.getSelectedItem().toString();
        String no = jTextField1.getText();
        
        
       

        Component f=null;

        //LocalDate bmonth  = datePicker1.getDate();

        if(netpay.getText().isEmpty()){
            JOptionPane.showMessageDialog(f," There Are Empty Space","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{

            int x = JOptionPane.showConfirmDialog(null,"Do u want to add data ?" , "Add To DB" , JOptionPane.INFORMATION_MESSAGE);

            if ( x == 0){
                try{

                    String w = " insert into fi_inputlast (no,Emp_ID,Name,NIC,Department,Basic,Bonus,Netpay,Date,Status) "
                    + "values('"+no+"' ,'"+empid+"' , '"+na+"' , '"+ni+"' , '"+depa+"' ,"
                    + " '"+bas+"' , '"+bon+"' , '"+net+"','"+nduedate+"', '"+stat+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();

                    //                String ww = " insert into fi_otherbill_backup (billno,billtype,billmonth,duedate,advance,amount,method,type,action) "
                    //                + "values('"+bno+"' , '"+btype+"' , '"+bmonth+"' , '"+nduedate+"' , '"+adva+"' , '"+amou+"' )";
                    //                pst = con.prepareStatement(ww);
                    //                pst.execute();

                    JOptionPane.showMessageDialog(null,"Complete !");
                    loadtable();
                    

                    namee.setText("");
                    nic.setText("");
                    jDateChooser1.setDate(null);
                    department.setSelectedIndex(0);
                    basic.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    overtime.setText("");
                    grosspay.setText("");
                    bonus.setText("");
                    epf.setText("");
                    etf.setText("");
                    deducation.setText("");
                    
                    incentives.setText("");
                    netpay.setText("");
                    workingdays.setText("");
                    jTextField1.setText("");
                    jComboBox1.setSelectedIndex(-1);
                    workingdays.setText("");
                  

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Complete !");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int row=jTable2.getSelectedRow();
        String click=(jTable2.getModel().getValueAt(row,0).toString());
        
        
//            String empid = jComboBox1.getSelectedItem().toString();
//        String na = namee.getText();
//        String ni = nic.getText();
//        String depa = department.getSelectedItem().toString();
//        String bas = basic.getText();
//        String bon  = bonus.getText();
//        String net  = netpay.getText();
//        Date nduedate = jDateChooser1.getDate();
//        String stat = jComboBox3.getSelectedItem().toString();
//        String no = jTextField1.getText();
//       

        int x = JOptionPane.showConfirmDialog(null,"Do u want to delete");

        if ( x== 0 ){

            try{

                String sql = " delete from fi_inputlast where no = '"+click+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();

                
//                   String w = " insert into fi_lastdelete (no,Emp_ID,Name,NIC,Department,Basic,Bonus,Netpay,Date,Status) "
//                    + "values('"+no+"' ,'"+empid+"' , '"+na+"' , '"+ni+"' , '"+depa+"' ,"
//                    + " '"+bas+"' , '"+bon+"' , '"+net+"','"+nduedate+"', '"+stat+"')";
//                    pst = con.prepareStatement(w);
//                    pst.execute();
                
                
                loadtable();
                JOptionPane.showMessageDialog(null,"Succesfull");

                
                    namee.setText("");
                    nic.setText("");
                    jDateChooser1.setDate(null);
                    department.setSelectedIndex(0);
                    basic.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    overtime.setText("");
                    grosspay.setText("");
                    bonus.setText("");
                    epf.setText("");
                    etf.setText("");
                    deducation.setText("");
                    
                    incentives.setText("");
                    netpay.setText("");
                      workingdays.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    namee.setText("");
                    nic.setText("");
                    jDateChooser1.setDate(null);
                    department.setSelectedIndex(0);
                    basic.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    overtime.setText("");
                    grosspay.setText("");
                    bonus.setText("");
                    epf.setText("");
                    etf.setText("");
                    deducation.setText("");
                    
                    incentives.setText("");
                    netpay.setText("");
                      workingdays.setText("");
                      jTextField1.setText("");
                      workingdays.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable2.getSelectedRow();
        String click = (jTable2.getModel().getValueAt(row, 0).toString());
        
         int x = JOptionPane.showConfirmDialog(null, "Do You Want To Update These Data? ","add to DB",JOptionPane.INFORMATION_MESSAGE);

        if( x == 0){
        
        String empid = jComboBox1.getSelectedItem().toString();
        String na = namee.getText();
        String ni = nic.getText();
        String depa = department.getSelectedItem().toString();
        String bas = basic.getText();
        String bon  = bonus.getText();
        String net  = netpay.getText();
        Date nduedate = jDateChooser1.getDate();
        String stat = jComboBox3.getSelectedItem().toString();
        String no = jTextField1.getText();
             
        
               try{
               
               String sql = " delete from fi_inputlast where no = '"+click+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                   
                   
                     String w = " insert into fi_inputlast (no,Emp_ID,Name,NIC,Department,Basic,Bonus,Netpay,Date,Status) "
                    + "values('"+no+"' ,'"+empid+"' , '"+na+"' , '"+ni+"' , '"+depa+"' ,"
                    + " '"+bas+"' , '"+bon+"' , '"+net+"','"+nduedate+"', '"+stat+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();


            JOptionPane.showMessageDialog(null, " Update Is Complete !");
            loadtable();
            
            namee.setText("");
                    nic.setText("");
                    jDateChooser1.setDate(null);
                    department.setSelectedIndex(0);
                    basic.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    overtime.setText("");
                    grosspay.setText("");
                    bonus.setText("");
                    epf.setText("");
                    etf.setText("");
                    deducation.setText("");
                    
                    incentives.setText("");
                    netpay.setText("");
                    jTextField1.setText("");
                    workingdays.setText("");
                
     
                
        
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
               } }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked



             DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        
                int row = this.jTable2.getSelectedRow();
                this.jTextField1.setText(dtm.getValueAt(row, 0).toString());
                this.jComboBox1.setSelectedItem(dtm.getValueAt(row, 1).toString());
                this.namee.setText(dtm.getValueAt(row, 2).toString());
                this.nic.setText(dtm.getValueAt(row, 3).toString());
                this.department.setSelectedItem(dtm.getValueAt(row, 4).toString());
                this.basic.setText(dtm.getValueAt(row, 5).toString());
                this.bonus.setText(dtm.getValueAt(row, 6).toString());
                this.netpay.setText(dtm.getValueAt(row, 7).toString());
               ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 8).toString());
               this.jComboBox3.setSelectedItem(dtm.getValueAt(row, 9).toString());











//        int row=jTable2.getSelectedRow();
//        String click=(jTable2.getModel().getValueAt(row,0).toString());
//
//        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
//
//        try{
//            String sql= " select * from  fi_inputlast where no = '"+click+"'";
//            pst = con.prepareStatement(sql);
//            rs = pst.executeQuery();
//            
//            //
//            
//            
//            
//            if(rs.next()){
//
//                   String no = rs.getString("no");
//                jTextField1.setText(no);
//                
//                String a1 = rs.getString("Emp_ID");
//                jLabel1.setText(a1);
//
//
//                
//                String a2 = rs.getString("Status");
//                jComboBox3.setSelectedItem(a2);
//                //
//                String a3 = rs.getString("Name");
//                namee.setText(a3);
//
//                String a4 = rs.getString("NIC");
//                nic.setText(a4);
//
//                String a5 = rs.getString("Department");
//                department.setSelectedItem(a5);
//                
//                String a6 = rs.getString("Basic");
//                jComboBox3.setSelectedItem(a6);
//                //
//                String a7 = rs.getString("Bonus");
//                namee.setText(a7);
//
//                String a8 = rs.getString("Netpay");
//                nic.setText(a8);
//                
//                String a9 = rs.getString("Status");
//                jComboBox3.setSelectedItem(a9);
//                
//                
////                Date da = rs.getDate("Date");
////                jDateChooser1.setDate(da);
//                
//                
//                
//                
//
//                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 8).toString());
//
//            }
//
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        Fi_Main am = new Fi_Main();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Home ho = new Home();
        ho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadtable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void basicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basicKeyTyped
         char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
    }//GEN-LAST:event_basicKeyTyped
    }
    private void workingdaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workingdaysKeyTyped
          char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_workingdaysKeyTyped
    
    private void overtimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_overtimeKeyTyped
            char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_overtimeKeyTyped

    private void bonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusKeyTyped
           char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_bonusKeyTyped

    private void grosspayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grosspayKeyTyped
            char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_grosspayKeyTyped

    private void epfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epfKeyTyped
            char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_epfKeyTyped

    private void etfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etfKeyTyped
           char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_etfKeyTyped

    private void deducationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deducationKeyTyped
           char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_deducationKeyTyped

    private void netpayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netpayKeyTyped
            char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_netpayKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
            char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        MessageFormat header = new MessageFormat("Report Print!");
        MessageFormat foter = new MessageFormat("page{0,number,integer}");
          
            try{

                jTable2.print(JTable.PrintMode.NORMAL,header,foter);
                
//                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "‪+"C:\\Users\\salit\\Documents\\ss.pdf");
                
                

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Try Again"); }
    }//GEN-LAST:event_jLabel12MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fi_salari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fi_salari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fi_salari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fi_salari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fi_salari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basic;
    private javax.swing.JTextField bonus;
    private javax.swing.JLabel date;
    private javax.swing.JTextField deducation;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField epf;
    private javax.swing.JTextField etf;
    private javax.swing.JTextField grosspay;
    private javax.swing.JTextField incentives;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField namee;
    private javax.swing.JTextField netpay;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField overtime;
    private javax.swing.JLabel time;
    private javax.swing.JTextField workingdays;
    // End of variables declaration//GEN-END:variables
}
