/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static org.hibernate.type.TypeFactory.basic;

/**
 *
 * @author BS
 */
public class fi_vehicle extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst= null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public fi_vehicle() {
        initComponents();
        con = DBconnect.connect();
        loadtable();
        showdate();
        showtime();
        
        getlastidfivehicle();
        fill1();
        
    }
    
     void fill1(){
        
        try {
            ResultSet rs = DB.getData("SELECT VID FROM vehicle");
            while(rs.next()){
            
                jComboBox2.addItem(rs.getString("VID"));
            
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     
    
         public void getlastidfivehicle(){
        
                try{
      String q = " SELECT No FROM fi_vehiclesalaryy ORDER BY No DESC LIMIT 1";
      pst = con.prepareStatement(q);
      rs = pst.executeQuery();

      while(rs.next()){
      //jLabel30.setText("");
      jLabel2.setText(rs.getString("No"));
        }
      
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }}
                
    public void loadtable(){
               try{
                String sql = " select * from fi_vehiclesalaryy ";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    
    
    
    
    final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd [ E ]");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime(){
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Owner", "NIC", "Deposite", "Rental", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1060, 240));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Vehicle_ID :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField18KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 30));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/pdf-icon.png"))); // NOI18N
        jLabel57.setToolTipText("See All");
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 50));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 100, 30));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Blue-Backup-B-icon(1).png"))); // NOI18N
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 40, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 190, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1080, 300));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 100, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 100, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("New");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 100, 30));

        jButton8.setFont(new java.awt.Font("Anklepants", 0, 18)); // NOI18N
        jButton8.setText("Insert");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ownar Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIC :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 30));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Deposite :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 80, 30));

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rental :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 50, 30));

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 180, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setBackground(new java.awt.Color(51, 255, 0));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One :-", "Confirmed And Pay", "Recheck Again" }));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 255, 0));
        jLabel23.setText("PAY SALARY");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 220, 100));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 180, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 180, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 50, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Make :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 60, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Year :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 60, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Model :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("L.No :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 30));

        jComboBox2.setBackground(new java.awt.Color(51, 255, 0));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Vehicle", "HM-4884", "LF-8235", "PV-6875", "PV-8885", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 30));

        jLabel1.setBackground(new java.awt.Color(51, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Vehicle NO :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Type :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Vehicle No :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 30));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1080, 250));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 10));

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("VEHICLE SALARY MAMAGEMENT");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 30));

        time.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 0));
        time.setText("time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 130, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 0));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 130, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/go_previous_blue.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Apps-Home-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyReleased
        String did = jTextField18.getText();

        try{

            String q = " Select * from fi_employeesalary where Emp_ID like '%"+did+"%'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField18KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String empid = jComboBox2.getSelectedItem().toString();
        String name = jTextField7.getText();
        String ni = jTextField13.getText();
        String stat = jComboBox3.getSelectedItem().toString();
        String depo = jTextField14.getText();
        String ren  = jTextField15.getText();
        //String net  = jTextField10.getText();
        String nduedate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
//        String stat = jComboBox3.getSelectedItem().toString();
String noo = jTextField1.getText();
        
        
       

        Component f=null;

        //LocalDate bmonth  = datePicker1.getDate();

        if(jTextField15.getText().isEmpty()){
            JOptionPane.showMessageDialog(f," There Are Empty Space","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{

            int x = JOptionPane.showConfirmDialog(null,"Do u want to add data ?" , "Add To DB" , JOptionPane.INFORMATION_MESSAGE);

            if ( x == 0){
                try{

                    String w = " insert into fi_vehiclesalaryy (No,Vehicle_No,Owner,NIC,Deposite,Rental,Date,Status) "
                    + "values('"+noo+"' ,'"+empid+"' , '"+name+"' , '"+ni+"' , '"+depo+"' ,"
                    + " '"+ren+"' , '"+nduedate+"' , '"+stat+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();

                    //                String ww = " insert into fi_otherbill_backup (billno,billtype,billmonth,duedate,advance,amount,method,type,action) "
                    //                + "values('"+bno+"' , '"+btype+"' , '"+bmonth+"' , '"+nduedate+"' , '"+adva+"' , '"+amou+"' )";
                    //                pst = con.prepareStatement(ww);
                    //                pst.execute();

                    
                    loadtable();
                     getlastidfivehicle();

                    jTextField12.setText("");
                    jTextField11.setText("");
                    jDateChooser1.setDate(null);
                    jComboBox2.setSelectedIndex(0);
                    jTextField9.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    jTextField8.setText("");
                    jTextField7.setText("");
                    jTextField13.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                     jTextField1.setText("");
                     jTextField2.setText("");
                     
                     JOptionPane.showMessageDialog(null,"Complete !");
//                    deducation.setText("");
//                    
//                    incentives.setText("");
//                    netpay.setText("");
                  

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"OOPS !");
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       String tmp = jComboBox2.getSelectedItem().toString();
       String sql = " select * from  vehicle where VID = ? ";
       
       try{
           pst = con.prepareStatement(sql);
           pst.setString(1, tmp);
           rs = pst.executeQuery();
           
           if ( rs.next()){
                String add1 = rs.getString("VID");
                jComboBox2.setSelectedItem(add1);
                
                String add2 = rs.getString("type");
                jTextField12.setText(add2);
                
                String add3 = rs.getString("model");
                jTextField11.setText(add3);
                
                String add4 = rs.getString("make");
                jTextField9.setText(add4);
                
               
                
                String add5 = rs.getString("year");
                jTextField8.setText(add5);
                
                String add6 = rs.getString("owner_name");
                jTextField7.setText(add6);
                
                String add7 = rs.getString("owner_nic");
                jTextField13.setText(add7);
                
                String add8 = rs.getString("deposit");
                jTextField14.setText(add8);
                
                String add9 = rs.getString("rental");
                jTextField15.setText(add9);
                
                
                
              
                
                
               
           }
       }
           catch (Exception e){
                   JOptionPane.showMessageDialog(null, e);
                   }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int row=jTable1.getSelectedRow();
        String click=(jTable1.getModel().getValueAt(row,0).toString());
        
         String empid = jComboBox2.getSelectedItem().toString();
        String name = jTextField7.getText();
        String ni = jTextField13.getText();
        String stat = jComboBox3.getSelectedItem().toString();
        String depo = jTextField14.getText();
        String ren  = jTextField15.getText();
        //String net  = jTextField10.getText();
        Date nduedate = jDateChooser1.getDate();
        String noo = jTextField1.getText();
       

        int x = JOptionPane.showConfirmDialog(null,"Do u want to delete");

        if ( x== 0 ){

            try{

                String sql = " delete from fi_vehiclesalaryy where No = '"+click+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();

                
                    String w = " insert into fivehicledelete (No,Vehicle_No,Owner,NIC,Deposite,Rental,Date,Status) "
                    + "values('"+noo+"' ,'"+empid+"' , '"+name+"' , '"+ni+"' , '"+depo+"' ,"
                    + " '"+ren+"' , '"+nduedate+"' , '"+stat+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();
                    
                    
                loadtable();
                

                
                    jTextField12.setText("");
                    jTextField11.setText("");
                    jDateChooser1.setDate(null);
                    jComboBox2.setSelectedIndex(0);
                    jTextField9.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    jTextField8.setText("");
                    jTextField7.setText("");
                    jTextField13.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    jTextField1.setText("");
                      jTextField2.setText("");
                      
                      JOptionPane.showMessageDialog(null,"Succesfull");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          jTextField12.setText("");
                    jTextField11.setText("");
                    jDateChooser1.setDate(null);
                    jComboBox2.setSelectedIndex(0);
                    jTextField9.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    jTextField8.setText("");
                    jTextField7.setText("");
                    jTextField13.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    jTextField1.setText("");
                      jTextField2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int row = jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(row, 0).toString());
        
         int x = JOptionPane.showConfirmDialog(null, "Do You Want To Update These Data? ","add to DB",JOptionPane.INFORMATION_MESSAGE);

        if( x == 0){
        
        String empid = jComboBox2.getSelectedItem().toString();
        String name = jTextField7.getText();
        String ni = jTextField13.getText();
        String stat = jComboBox3.getSelectedItem().toString();
        String depo = jTextField14.getText();
        String ren  = jTextField15.getText();
        //String net  = jTextField10.getText();
        Date nduedate = jDateChooser1.getDate();
        String noo = jTextField1.getText();
        
             
        
               try{
               
                 String sql = " delete from fi_vehiclesalaryy where No = '"+click+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                   
                   
                     String w = " insert into fi_vehiclesalaryy (No,Vehicle_No,Owner,NIC,Deposite,Rental,Date,Status) "
                    + "values('"+noo+"' ,'"+empid+"' , '"+name+"' , '"+ni+"' , '"+depo+"' ,"
                    + " '"+ren+"' , '"+nduedate+"' , '"+stat+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();
                   
                    pst = con.prepareStatement(w);
                    pst.execute();

            JOptionPane.showMessageDialog(null, " Update Is Complete !");
            loadtable();
            
                    jTextField12.setText("");
                    jTextField11.setText("");
                    jDateChooser1.setDate(null);
                    jComboBox2.setSelectedIndex(0);
                    jTextField9.setText("");
                    jComboBox3.setSelectedIndex(0);
                    
                    jTextField8.setText("");
                    jTextField7.setText("");
                    jTextField13.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    jTextField1.setText("");
                      jTextField2.setText("");
                
     
                
        
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
               } }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        String click=(jTable1.getModel().getValueAt(row,0).toString());

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        try{
            String sql= " select * from  fi_vehiclesalaryy where No = '"+click+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){

//                String a1 = rs.getString("Vehicle_No");
//                jComboBox2.setSelectedItem(a1);
                
                String noo = rs.getString("No");
                jTextField1.setText(noo);
                

//                String select = rs.getString("didd");
//                jComboBox1.setSelectedItem(select);
                
                String a2 = rs.getString("Status");
                jComboBox3.setSelectedItem(a2);
                //
                String a3 = rs.getString("Vehicle_No");
                jTextField2.setText(a3);
//
                String a4 = rs.getString("Owner");
                jTextField7.setText(a4);
                
                String nic = rs.getString("NIC");
                jTextField13.setText(nic);
//
                String deposite = rs.getString("Deposite");
                jTextField14.setText(deposite);
                
                String rental = rs.getString("Rental");
                jTextField15.setText(rental);
//
//                String deposite = rs.getString("Deposite");
//                jTextField7.setText(deposite);
                
                
                
                

                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 6).toString());

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        Fi_Main am = new Fi_Main();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Home ho = new Home();
        ho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked

        MessageFormat header = new MessageFormat("Report Print!");
        MessageFormat foter = new MessageFormat("page{0,number,integer}");

        try{

            jTable1.print(JTable.PrintMode.NORMAL,header,foter);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Try Again");
        }
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked

              //  int row = jTable1.getSelectedRow();
              //  String click = (jTable1.getModel().getValueAt(row, 0).toString());

        try{

            String sq1 = " select * from  fivehicledelete where No= '"+jTextField3.getText()+"'";
            pst = con.prepareStatement(sq1);
            rs = pst.executeQuery();

            if(rs.next()){
                String a1 = rs.getString("No");

                String a2 = rs.getString("Vehicle_No");

                String a3 = rs.getString("Owner");

                String a4 = rs.getString("NIC");

                String a5 = rs.getString("Deposite");

                String a6 = rs.getString("Rental");

                String a7 = rs.getString("Date");
                

                String a8 = rs.getString("Status");
                
                
                String q = " delete from fivehicledelete where No = '"+jTextField3.getText()+"'";
                pst = con.prepareStatement(q);
                pst.execute(); 
                
                
                String w = " insert into fi_vehiclesalaryy (No,Vehicle_No,Owner,NIC,Deposite,Rental,Date,Status) "
                    + "values('"+a1+"' ,'"+a2+"' , '"+a3+"' , '"+a4+"' , '"+a5+"' ,"
                    + " '"+a6+"' , '"+a7+"' , '"+a8+"')";
                    pst = con.prepareStatement(w);
                    pst.execute();

                
                loadtable();
                JOptionPane.showMessageDialog(null, " No :" +a1+ " Recovery is Successfull");
                jTextField3.setText("");
                
            }

        } catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
      
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        char inumber = evt.getKeyChar();
        if(!(Character.isDigit(inumber)) || (inumber == KeyEvent.VK_BACK_SPACE)|| (inumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fi_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fi_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fi_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fi_vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fi_vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
