/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tharaka
 */
public class Stock_Entry extends javax.swing.JFrame {

    /**
     * Creates new form Stock_Entry
     */
        
    PreparedStatement pst = null;
    Connection con = null;
    ResultSet rs = null;
    
    public Stock_Entry() {
        initComponents();
                
        con = DBconnect.connect();
        tableload();
        
        showdate();
        showtime();
    }
    
    final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime()
    {
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
    }
   
    void loadtable()
    {
        try
        {
            String sql="Select * from  stock_entry Order by BarCode";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e)
        {
            
        }
                
    }
    
            
    public void tableload()
    {
        try{
        //String lod = "SELECT EmpId as Emp_ID, FirstName as f,LastName as l,TelNo as t,Dateofbirth as d,Nicnumber as n,l1 as l,l2 as da,City as c,Gender as g,Age as a FROM my1 order by EmpId";
       
        String lod ="SELECT BarCode as Asset_Code , Item_Name , Category , Manufacture,Date,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,Current_Total,Supplier_Phone as a FROM stock_entry order by BarCode";
        pst = con.prepareStatement(lod);
        rs = pst.executeQuery();
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
        
    boolean validatePhone(String val)
    {
        if(val.startsWith("07") || val.startsWith("+94"))
        {
            if(val.startsWith("+94"))
            {
                if(val.length()==12)
                {
                    return true;
                }
                else return false;
            }
            else if(val.length()==10)
            {
                return true;
            }
            else return false;
        }
        String ph_pattern="^\\+?[0-9.()-](10,25)$";
        if(val.length()==10)
        {
            return true;
        }
    else return false;
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 219, 60));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/cal1.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 40, 60));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/clock2.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 40, 80));

        date.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 150, 40));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LogOut");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/mlabel.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 20, 440, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/employee.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 110));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 1310, 10));

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("All right reserved. Wijaya Digital Printers [2018]");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, 360, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Item Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 112, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Name :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Category :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manufacture :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Unit Price :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 130, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 152, 260, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 260, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 153));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category", "Stationary", "Marker Pen", "Hard Board", "Ink Pack", "Knife", "Laser Bulb", "DVD", "CD", "Cable", "Roller", "Other" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 260, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 260, 30));

        jDateChooser1.setDateFormatString("yyyy.MM.dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 260, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 260, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 260, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 260, 30));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 260, 30));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 260, 30));

        jDateChooser2.setDateFormatString("yyyy.MM.dd");
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 260, 30));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 260, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Supplier ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 150, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Supplier Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 150, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Invoice Number");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 150, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Invoice Amount");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 150, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Purchased Date");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 160, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Current Total");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 150, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 0));
        jLabel21.setText("Invoice Details");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 170, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1090, 190));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 0));
        jButton4.setText("Search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton4KeyReleased(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 190, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 0));
        jButton3.setText("Add Item");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 200, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 0));
        jButton5.setText("Update");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, 200, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 153, 0));
        jButton6.setText("Recover");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 530, 200, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("Clear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, 200, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 153, 0));
        jButton7.setText("Delete item");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 470, 200, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Asset Code");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, 30));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 200, 30));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Qty", "20", "50", "100", "200", "500", "500<" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Asset Code :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 130, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Supplier Phone No");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, 30));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 260, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Qty. :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 130, 30));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1080, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/go_previous_blue.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1360, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        String BarCode = jTextField6.getText();
        //String iname = jTextField12.getText();

        try{
            String sql ="select * from stock_entry where BarCode like '%"+BarCode+"%'";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ro = jTable1.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        int row = this.jTable1.getSelectedRow();
        this.jTextField1.setText(dtm.getValueAt(row, 0).toString());
        this.jTextField2.setText(dtm.getValueAt(row, 1).toString());
        this.jComboBox1.setSelectedItem(dtm.getValueAt(row, 2).toString());
        this.jTextField3.setText(dtm.getValueAt(row, 3).toString());
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 4).toString());
        this.jTextField4.setText(dtm.getValueAt(row, 5).toString());
        this.jComboBox2.setSelectedItem(dtm.getValueAt(row, 6).toString());
        this.jTextField7.setText(dtm.getValueAt(row, 7).toString());
        this.jTextField8.setText(dtm.getValueAt(row, 8).toString());
        this.jTextField9.setText(dtm.getValueAt(row, 9).toString());
        this.jTextField10.setText(dtm.getValueAt(row, 10).toString());
        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(dtm.getValueAt(row, 11).toString());
        this.jTextField11.setText(dtm.getValueAt(row, 12).toString());
        this.jTextField13.setText(dtm.getValueAt(row, 13).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        String pn = jTextField13.getText();
         if(validatePhone(pn))
         {
        
        String BarCode = jTextField1.getText();
        String Item_Name = jTextField2.getText();
        String Category = jComboBox1.getSelectedItem().toString();
        String Manufacture = jTextField3.getText();
        String Date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String Unit_Price = jTextField4.getText();
        String Qty = jComboBox2.getSelectedItem().toString();
        String Supplier_ID = jTextField7.getText();
        String Supplier_Name = jTextField8.getText();
        String Invoice_No = jTextField9.getText();
        String Invoice_Amount = jTextField10.getText();
        String Purchase_Date = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String Current_Total = jTextField11.getText();
        String Supplier_Phone = jTextField13.getText();       
        int x = JOptionPane.showConfirmDialog(null, " Do You want to Add ?", "add to DB", JOptionPane.INFORMATION_MESSAGE);

        {
            if(BarCode.equals("")||Item_Name.equals("")||Category.equals("")||Manufacture.equals("")||Date.equals("")||Unit_Price.equals("") ||Qty.equals("")||Supplier_ID.equals("")||Supplier_Name.equals("")||Invoice_No.equals("") ||Invoice_Amount.equals("")||Purchase_Date.equals("")||Current_Total.equals("")||Supplier_Phone.equals(""))
            {
            JOptionPane.showMessageDialog(this, "Some Fields are empty!!");
            //----------------------------------------------------------------------------------------//
             Color color=new Color(230,130,130); 
            if(jTextField1.getText().equals(""))
                jTextField1.setBackground(color);
            if(jTextField2.getText().equals(""))
                jTextField2.setBackground(color);
            if(jComboBox1.getSelectedItem().toString().equals("select"))
                jComboBox1.setBackground(color);
            if(jTextField3.getText().equals(""))
                jTextField3.setBackground(color);
            if(jTextField4.getText().equals(""))
                jTextField4.setBackground(color);
            if(jComboBox2.getSelectedItem().toString().equals("select"))
                jComboBox2.setBackground(color);
            if(jTextField7.getText().equals(""))
                jTextField7.setBackground(color);
            if(jTextField8.getText().equals(""))
                jTextField8.setBackground(color);
             if(jTextField9.getText().equals(""))
                jTextField9.setBackground(color);
            if(jTextField10.getText().equals(""))
                jTextField10.setBackground(color);
             if(jTextField11.getText().equals(""))
                jTextField11.setBackground(color);
            if(jTextField13.getText().equals(""))
                jTextField13.setBackground(color);
            
            
            
            //-----------------------------------------------------------------------------------------//
            return;
        
            }
            else
            {
                try
            {   
                String s  = " insert into stock_entry(BarCode , Item_Name , Category , Manufacture,Date,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,Current_Total,Supplier_Phone  )  "
                + "values ('"+BarCode+"' , '"+Item_Name+"', '"+Category+"' , '"+Manufacture+"', '"+Date+"' , '"+Unit_Price+"', '"+Qty+"', '"+Supplier_ID+"' , '"+Supplier_Name+"' , '"+Invoice_No+"' , '"+Invoice_Amount+"' , '"+Purchase_Date+"', '"+Current_Total+"', '"+Supplier_Phone+"') ";
                pst = con.prepareStatement(s);
                pst.execute();

//                String bup  = " insert into stock_reurn_last(BarCode , Item_Name , Category , Manufacture,Date,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,Current_Total  )   "
//                + "values ('"+BarCode+"' , '"+Item_Name+"', '"+Category+"' , '"+Manufacture+"', '"+Date+"' , '"+Unit_Price+"', '"+Qty+"', '"+Supplier_ID+"' , '"+Supplier_Name+"' , '"+Invoice_No+"' , '"+Invoice_Amount+"' , '"+Purchase_Date+"', '"+Current_Total+"') ";
//                pst = con.prepareStatement(s);
//                pst.execute();

                // getentry_value();
                loadtable();
                JOptionPane.showMessageDialog(this,"Complete !");

                jTextField1.setText("");
                jTextField2.setText("");
                jComboBox1.setSelectedIndex(0);
                jTextField3.setText("");
                jDateChooser1.setDate(null);
                jTextField4.setText("");
                jComboBox2.setSelectedIndex(0);
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jDateChooser2.setDate(null);
                jTextField11.setText("");
                jTextField13.setText("");                          
            }  
            catch(Exception e)
                {
                JOptionPane.showMessageDialog(this,e);
                System.out.println(e);                   
                }
            }   
        }
                    } 
            else 
            {
                 JOptionPane.showMessageDialog(this," Phone Number Invalide  !");
            }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String pn = jTextField13.getText();
         if(validatePhone(pn))
         {
        int x = JOptionPane.showConfirmDialog(null,"Update");

        if(x==0)
        {            
        String BarCode = jTextField1.getText();
        String Item_Name = jTextField2.getText();
        String Category = jComboBox1.getSelectedItem().toString();
        String Manufacture = jTextField3.getText();
        String Date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String Unit_Price = jTextField4.getText();
        String Qty = jComboBox2.getSelectedItem().toString();
        String Supplier_ID = jTextField7.getText();
        String Supplier_Name = jTextField8.getText();
        String Invoice_No = jTextField9.getText();
        String Invoice_Amount = jTextField10.getText();
        String Purchase_Date = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String Current_Total = jTextField11.getText();
        String Supplier_Phone = jTextField13.getText();

            try
            {
                String sq = "UPDATE stock_entry SET BarCode = '"+BarCode+"' , Item_Name = '"+Item_Name+"', Category = '"+Category+"' , Manufacture = '"+Manufacture+"', Date = '"+Date+"' , Unit_Price = '"+Unit_Price+"', Qty = '"+Qty+"', Supplier_ID = '"+Supplier_ID+"' , Supplier_Name = '"+Supplier_Name+"' , Invoice_No = '"+Invoice_No+"' , Invoice_Amount = '"+Invoice_Amount+"' , Purchase_Date = '"+Purchase_Date+"', Current_Total = '"+Current_Total+"' , Supplier_Phone = '"+Supplier_Phone+"' WHERE BarCode = '"+BarCode+"'";
                pst = con.prepareStatement(sq);
                pst.execute();
                tableload();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
                           } 
            else 
            {
                 JOptionPane.showMessageDialog(this," Phone Number Invalide  !");
            }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

       String BarCode = jTextField1.getText();
        String Item_Name = jTextField2.getText();
        String Category = jComboBox1.getSelectedItem().toString();
        String Manufacture = jTextField3.getText();
        Date Date = jDateChooser1.getDate();
        String Unit_Price = jTextField4.getText();
        String Qty = jComboBox2.getSelectedItem().toString();
        String Supplier_ID = jTextField7.getText();
        String Supplier_Name = jTextField8.getText();
        String Invoice_No = jTextField9.getText();
        String Invoice_Amount = jTextField10.getText();
        Date Purchase_Date = jDateChooser2.getDate();
        String Current_Total = jTextField11.getText();
        String Supplier_Phone = jTextField13.getText();
        
        String bar = jTextField6.getText();
//
//        int x = JOptionPane.showConfirmDialog(null, " Do You want to Return ?", "add to DB", JOptionPane.INFORMATION_MESSAGE);
//
//        {
//            
//            if( x==0){
//
//            try{
//                
//                String s  = " insert into stock_entry(BarCode , Item_Name , Category , Manufacture,Date,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,Current_Total,Supplier_Phone  )  "
//                + "values ('"+BarCode+"' , '"+Item_Name+"', '"+Category+"' , '"+Manufacture+"', '"+Date+"' , '"+Unit_Price+"', '"+Qty+"', '"+Supplier_ID+"' , '"+Supplier_Name+"' , '"+Invoice_No+"' , '"+Invoice_Amount+"' , '"+Purchase_Date+"', '"+Current_Total+"', '"+Supplier_Phone+"') ";
//                pst = con.prepareStatement(s);
//                pst.execute();
//
//                String q  = " delete from stock_reurn_end where BarCode = '"+BarCode+"'";
//                pst = con.prepareStatement(q);
//                pst.execute();
//
//                // getentry_value();
//                loadtable();
//                
//                JOptionPane.showMessageDialog(this,"Complete !");
//
//                jTextField1.setText("");
//                jTextField2.setText("");
//                jComboBox1.setSelectedIndex(0);
//                jTextField3.setText("");
//                jDateChooser1.setDate(null);
//                jTextField4.setText("");
//                jComboBox2.setSelectedIndex(0);
//                jTextField7.setText("");
//                jTextField8.setText("");
//                jTextField9.setText("");
//                jTextField10.setText("");
//                jDateChooser2.setDate(null);
//                jTextField11.setText("");
//                jTextField13.setText("");
//
//                
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(null,e);
//
//            }
//
//        }
//        }



       try{

            String sq1 = " select * from  stock_reurn_end where BarCode= '"+bar+"'";
            pst = con.prepareStatement(sq1);
            rs = pst.executeQuery();

            if(rs.next()){
                String a1 = rs.getString("BarCode");

                String a2 = rs.getString("Item_Name");

                String a3 = rs.getString("Category");

                String a4 = rs.getString("Manufacture");

                String a5 = rs.getString("Date1");

                String a6 = rs.getString("Unit_Price");

                String a7 = rs.getString("Qty");
                
                
                
                String a8 = rs.getString("Supplier_ID");

                String a9 = rs.getString("Supplier_Name");

                String a10= rs.getString("Invoice_No");

                String a11 = rs.getString("Invoice_Amount");

                String a12 = rs.getString("Purchase_Date");

                String a13 = rs.getString("Current_Total");

                String a14 = rs.getString("Supplier_Phone");

                String q  = " delete from stock_reurn_end where BarCode = '"+bar+"'";
                pst = con.prepareStatement(q);
                pst.execute();
                
                
                
                  String s  = " insert into stock_entry (BarCode ,Item_Name ,Category ,"
                          + "Manufacture,Date,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,"
                          + "Current_Total,Supplier_Phone  )  "
                + "values ('"+a1+"' , '"+a2+"', '"+a3+"' , '"+a4+"', '"+a5+"' , '"+a6+"', '"+a7+"', "
                          + "'"+a8+"' , '"+a9+"' , '"+a10+"' , '"+a11+"' , '"+a12+"', "
                          + "'"+a13+"', '"+a14+"') ";
                pst = con.prepareStatement(s);
                pst.execute();

                JOptionPane.showMessageDialog(null, " Bill No :" +bar+ " Recovery is Successfull");
                jTextField3.setText("");
                loadtable();
            }

        } catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }





























    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        jTextField1.setText(null);
        jTextField2.setText(null);
        jComboBox1.setSelectedIndex(0);
        jTextField3.setText(null);
        jDateChooser1.setDate(null);
        jTextField4.setText(null);
        jComboBox2.setSelectedIndex(0);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jDateChooser2.setDate(null);
        jTextField11.setText(null);
        jTextField13.setText(null);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    
        this.dispose();
        new Stock_PanelSet().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        
        String BarCode = jTextField1.getText();
        String Item_Name = jTextField2.getText();
        String Category = jComboBox1.getSelectedItem().toString();
        String Manufacture = jTextField3.getText();
        Date Date1 = jDateChooser1.getDate();
        String Unit_Price = jTextField4.getText();
        String Qty = jComboBox2.getSelectedItem().toString();
        String Supplier_ID = jTextField7.getText();
        String Supplier_Name = jTextField8.getText();
        String Invoice_No = jTextField9.getText();
        String Invoice_Amount = jTextField10.getText();
        Date Purchase_Date = jDateChooser2.getDate();
        String Current_Total = jTextField11.getText();
        String Supplier_Phone = jTextField13.getText();

        int x = JOptionPane.showConfirmDialog(null, " Do You want to Return ?", "add to DB", JOptionPane.INFORMATION_MESSAGE);

        {
            if( x==0){

            try{
                String s  = " insert into stock_reurn_end(BarCode , Item_Name , Category , Manufacture,Date1,Unit_Price,Qty,Supplier_ID,Supplier_Name,Invoice_No,Invoice_Amount,Purchase_Date,Current_Total,Supplier_Phone  )  "
                + "values ('"+BarCode+"' , '"+Item_Name+"', '"+Category+"' , '"+Manufacture+"', '"+Date1+"' , '"+Unit_Price+"', '"+Qty+"', '"+Supplier_ID+"' , '"+Supplier_Name+"' , '"+Invoice_No+"' , '"+Invoice_Amount+"' , '"+Purchase_Date+"', '"+Current_Total+"', '"+Supplier_Phone+"') ";
                pst = con.prepareStatement(s);
                pst.execute();

                String q  = " delete from stock_entry where BarCode = '"+BarCode+"'";
                pst = con.prepareStatement(q);
                pst.execute();

                // getentry_value();
                loadtable();
                
                JOptionPane.showMessageDialog(this,"Complete !");

                jTextField1.setText("");
                jTextField2.setText("");
                jComboBox1.setSelectedIndex(0);
                jTextField3.setText("");
                jDateChooser1.setDate(null);
                jTextField4.setText("");
                jComboBox2.setSelectedIndex(0);
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jDateChooser2.setDate(null);
                jTextField11.setText("");
                jTextField13.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }

        }
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyReleased
        
        String BarCode = jTextField6.getText();
        String iname = jTextField6.getText();
        //String acode = jTextField1.getText();
        
        if(BarCode.equals(""))
            {
            JOptionPane.showMessageDialog(this, "Please Enter BarCode ,Do you want find details!!");
            //----------------------------------------------------------------------------------------//
             Color color=new Color(230,130,130); 

             if(jTextField6.getText().equals(""))
                jTextField6.setBackground(color);        
            //-----------------------------------------------------------------------------------------//
            return;
        
            }
            else
            {
        try
        {
            String sql ="select * from stock_entry where BarCode = '"+BarCode+"'";

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {}
        
        }
    }//GEN-LAST:event_jButton4KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
     
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      
        this.dispose();
        new Stock_PanelSet().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
