/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wijaya;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BS
 */
public class yasi_client extends javax.swing.JFrame {

   PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    Connection con = null;
    
    public yasi_client() {
        initComponents();
        con = DBconnect.connect();
        loadtable();
        
        showdate();
        showtime();
        fill1();
        fill12();
        
    }
    
    
     void fill1(){
        jComboBox3.removeAllItems();
        try {
            ResultSet rs = DB.getData("SELECT CID FROM customers");
            while(rs.next()){
            
                jComboBox3.addItem(rs.getString("CID"));
            
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
      void fill12(){
        jTextField7.removeAllItems();
        try {
            ResultSet rs = DB.getData("SELECT f_name FROM customers");
            while(rs.next()){
            
                jTextField7.addItem(rs.getString("f_name"));
            
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     
     
     final void showdate(){
        Date d = new Date();
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd [ E ]");
        String datee = adf.format(d);
        date.setText(datee);
        
         }
    
    void showtime(){
        
        new Timer(0,(ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
            String timee = sdf.format(d);
            time.setText(timee);
        }).start();
   
    }
    
    
     void loadtable(){
        
            try{
                String sql = " select no as No , name as Name , clId as Cus_ID , work as Cus_NIC, email as E_Mail ,"
                        + " address as Address, mono as Mobile_1 , mono2 as Mobile_2 , custype as Cus_type from su_client order by no ASC ";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                getlastidclient();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
     
     public void getlastidclient(){
        
                try{
      String q = " SELECT no FROM su_client ORDER BY no DESC LIMIT 1";
      pst = con.prepareStatement(q);
      rs = pst.executeQuery();

      while(rs.next()){
      //jLabel30.setText("");
      jLabel9.setText(rs.getString("no"));
        }
      
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
        
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField13 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 204, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mobile No:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer NIC :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer ID:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer type:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 140, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Silver", "Gold", "Platinum" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 150, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 30));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 300, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 450, 30));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 170, 30));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("L.No :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 70, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 120, 30));

        jButton3.setFont(new java.awt.Font("Anklepants", 0, 18)); // NOI18N
        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 140, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Update Profile");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, 120, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Delete Profile");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 120, 30));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs." }));
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("/");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 30, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 180, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("No :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 30));

        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 122, 240, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1280, 380));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Mobile No", "Work", "Email", "Address", "Driver", "Customer type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1260, 170));

        jTextField13.setBackground(new java.awt.Color(51, 51, 51));
        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField13KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 30));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 80, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name OR CID :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.setOpaque(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 80, 30));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/2-Hot-Printer-icon.png"))); // NOI18N
        jLabel64.setToolTipText("See All");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 40, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 40, 30));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Blue-Backup-B-icon(1).png"))); // NOI18N
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 40, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1280, 230));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 0));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 140, 20));

        time.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 0));
        time.setText("time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 120, 20));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CLIENT INFORMATION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 10));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/go_previous_blue.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 40, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesfor/Apps-Home-icon.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row=jTable1.getSelectedRow();
        String click=(jTable1.getModel().getValueAt(row,0).toString());

        try{
            String sql=" select * from su_client where no = '"+click+"' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){

                String noo = rs.getString("no");
                jTextField2.setText(noo);
                
                String a1 = rs.getString("name");
                System.out.println(a1);
                jTextField7.setSelectedItem(a1);
                
                String ty = rs.getString("type");
                jComboBox2.setSelectedItem(ty);

                String a2 = rs.getString("clId");
                jComboBox3.setSelectedItem(a2);
                //
                String a3 = rs.getString("work");
                jTextField9.setText(a3);

                String a4 = rs.getString("email");
                jTextField10.setText(a4);

                String a5 = rs.getString("address");
                jTextField11.setText(a5);

                String a6 = rs.getString("mono");
                jTextField12.setText(a6);
                
                String mon2 = rs.getString("mono2");
                jTextField3.setText(mon2);

                String a7 = rs.getString("custype");
                jComboBox1.setSelectedItem(a7);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyReleased

        String name = jTextField13.getText();
        
        

        try{
            String sql = " select * from su_client where name like '%"+name+"%'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
       

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jTextField13KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String y = jComboBox3.getSelectedItem().toString();
        
        if(y.isEmpty() ){
        
            JOptionPane.showMessageDialog(null, "Please Enter Customer ID" , "Warning !" , JOptionPane.WARNING_MESSAGE);
        
        }
        
        else{
        int x = JOptionPane.showConfirmDialog(null,"Do You Want To Add ?? " ,"Add To System" , JOptionPane.INFORMATION_MESSAGE);
        
        if(x == 0){
        
        
        String noo = jTextField2.getText();
        String com =   jComboBox1.getSelectedItem().toString();
        String name = jTextField7.getSelectedItem().toString();
        String clId = jComboBox3.getSelectedItem().toString();
        String work = jTextField9.getText();
        String email = jTextField10.getText();
        String addr = jTextField11.getText();
        String mo = jTextField12.getText();
        String mono = jTextField3.getText();
        String type = jComboBox2.getSelectedItem().toString();

        try{

            String sql = "insert into su_client (no ,name ,type,clId ,work ,email ,address ,mono , mono2 , custype ) "
                    + "values('"+noo+"','"+name+"' ,'"+type+"' ,'"+clId+"' , '"+work+"' , '"+email+"' , '"+addr+"' , '"+mo+"' ,'"+mono+"' ,'"+com+"')";
            pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Complete !");
            loadtable();
            jComboBox1.setSelectedIndex(0);
            jTextField7.setSelectedItem(0);
            jComboBox3.setSelectedIndex(-1);
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
        
        }   catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int row=jTable1.getSelectedRow();
        String click=(jTable1.getModel().getValueAt(row,0).toString());
        
        String noo = jTextField2.getText();
        String com =   jComboBox1.getSelectedItem().toString();
        String name = jTextField7.getSelectedItem().toString();
        String clId =  jComboBox3.getSelectedItem().toString();
        String work = jTextField9.getText();
        String email = jTextField10.getText();
        String addr = jTextField11.getText();
        String mo = jTextField12.getText();
        String mono = jTextField3.getText();
        String type = jComboBox2.getSelectedItem().toString();

        int x = JOptionPane.showConfirmDialog(null,"Do u want to delete");

        if ( x== 0 ){

            try{

                String sql = " delete from su_client where no = '"+click+"' ";
                pst = con.prepareStatement(sql);
                pst.execute();
                
            String sq = "insert into su (no ,name ,type,clId ,work ,email ,address ,mono , mono2 , custype ) "
            + "values('"+noo+"','"+name+"' ,'"+type+"' ,'"+clId+"' , '"+work+"' , '"+email+"' , '"+addr+"' , '"+mo+"' ,'"+mono+"' ,'"+com+"')";
            pst = con.prepareStatement(sq);
            pst.execute();
                
                
                JOptionPane.showMessageDialog(null, "complete");
                loadtable();

                jComboBox1.setSelectedIndex(0);
                jTextField7.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(-1);
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jComboBox2.setSelectedIndex(0);
                jTextField3.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jComboBox1.setSelectedIndex(0);
          jTextField7.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(-1);
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jComboBox2.setSelectedIndex(0);
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int row = jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(row, 0).toString());
        
         int x = JOptionPane.showConfirmDialog(null, "Do You Want To Update These Data? ","add to DB",JOptionPane.INFORMATION_MESSAGE);

        if( x == 0){
        
          String noo = jTextField2.getText();
        String com =   jComboBox1.getSelectedItem().toString();
        String name =   (String) jTextField7.getSelectedItem();
        String clId = jComboBox3.getSelectedItem().toString();
        String work = jTextField9.getText();
        String email = jTextField10.getText();
        String addr = jTextField11.getText();
        String mo = jTextField12.getText();
        String mono = jTextField3.getText();
        String type = jComboBox2.getSelectedItem().toString();
        
             
        
               try{
               
                String q = " delete from su_client where no = '"+click+"'";
                pst = con.prepareStatement(q);
                pst.execute();
                   
                   
                 String sql = "insert into su_client (no ,name ,type,clId ,work ,email ,address ,mono , mono2 , custype ) "
                    + "values('"+noo+"','"+name+"' ,'"+type+"' ,'"+clId+"' , '"+work+"' , '"+email+"' , '"+addr+"' , '"+mo+"' ,'"+mono+"' ,'"+com+"')";
            pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Complete !");
            loadtable();
            jComboBox1.setSelectedIndex(0);
              jTextField7.setSelectedIndex(0);
             jComboBox3.setSelectedIndex(-1);
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jComboBox2.setSelectedIndex(0);
            jTextField2.setText("");
            jTextField3.setText("");
                
     
                
        
               }catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
               } }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        char inum = evt.getKeyChar();
        if(!(Character.isDigit(inum) || (inum == KeyEvent.VK_DELETE) || (inum == KeyEvent.VK_BACKSPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
         char inum = evt.getKeyChar();
        if(!(Character.isDigit(inum) || (inum == KeyEvent.VK_DELETE) || (inum == KeyEvent.VK_BACKSPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
            
            String clid = jTextField4.getText();
        
            try{
            String sq = " select * from su_client where clId like '%"+clid+"%'";
            pst = con.prepareStatement(sq);
            rs2 = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs2));
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
            MessageFormat header = new MessageFormat("Report Print!");
           MessageFormat foter = new MessageFormat("page{0,number,integer}");
          
            try{

                jTable1.print(JTable.PrintMode.NORMAL,header,foter);

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error !! Please Try Again."); }
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
       char inum = evt.getKeyChar();
        if(!(Character.isDigit(inum) || (inum == KeyEvent.VK_DELETE) || (inum == KeyEvent.VK_BACKSPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
         char inum = evt.getKeyChar();
        if(!(Character.isDigit(inum) || (inum == KeyEvent.VK_DELETE) || (inum == KeyEvent.VK_BACKSPACE))){
            evt.consume();
            //jTextField4.setBackground(new Color(255,0,0));
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        yasi_main am = new yasi_main();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked

      try{

            String sq1 = " select * from  su where no= '"+jTextField1.getText()+"'";
            pst = con.prepareStatement(sq1);
            rs = pst.executeQuery();

            if(rs.next()){
                
                String noo = rs.getString("no");
                                
                String a1 = rs.getString("name");
                                
                String ty = rs.getString("type");
                
                String a2 = rs.getString("clId");
                                
                String a3 = rs.getString("work");
               
                String a4 = rs.getString("email");
                
                String a5 = rs.getString("address");
               
                String a6 = rs.getString("mono");
                                
                String mon2 = rs.getString("mono2");
                
                String a7 = rs.getString("custype");
                
            String sql = "insert into su_client (no ,name ,type,clId ,work ,email ,address ,mono , mono2 , custype ) "
            + "values('"+noo+"','"+a1+"' ,'"+ty+"' ,'"+a2+"' , '"+a3+"' , '"+a4+"' , '"+a5+"' , '"+a6+"' ,"
                    + "'"+mon2+"' ,'"+a7+"')";
            pst = con.prepareStatement(sql);
            pst.execute();
            
                String q = " delete from su where no = '"+jTextField1.getText()+"'";
                pst = con.prepareStatement(q);
                pst.execute();

                JOptionPane.showMessageDialog(null, " No :" +noo+ " Recovery is Successfull");
                jTextField1.setText("");
                loadtable();
                
                
       
            }

        } catch(Exception e){

            JOptionPane.showMessageDialog(null, "Recover is Unsuccesfull.. ");

        }
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
                Home ho = new Home();
                ho.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
//           String tmp = jComboBox1.getSelectedItem().toString();
//       String sql = " select * from customers where CID = ? ";
//       
//       try{
//           pst = con.prepareStatement(sql);
//           pst.setString(1, tmp);
//           rs = pst.executeQuery();
//           
//           if ( rs.next()){
//                String add4 = rs.getString("CID");
//                jComboBox4.setSelectedItem(add4);
//                
//                String add = rs.getString("f_name");
//                jLabel13.setText(add);
//                
//
//                
//                
//                
//               
//           }
//       }
//           catch (Exception e){
//                   JOptionPane.showMessageDialog(null, e);
//                   }
//                   
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yasi_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yasi_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yasi_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yasi_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yasi_client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
